_wandb:
    value:
        cli_version: 0.23.1
        e:
            33hx5zsjqi0vo617lec41pux18m0s9vd:
                args:
                    - --epochs
                    - "150"
                    - --dataset
                    - affi
                    - --alpha
                    - "1.0"
                    - --dropout
                    - "0.1"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "489997189120"
                        used: "66490368000"
                email: tzuhsuan5684@gmail.com
                executable: /home/annie/miniconda3/envs/neural_forecasting/bin/python
                git:
                    commit: 24d2db2b76991d6cfc50fa7404a64ab1d55399eb
                    remote: https://github.com/YuunJiee/NeuralForecasting.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-234165ac-6cc3-2a6b-93ee-7f9980e58c90
                    - architecture: Ampere
                      cudaCores: 3584
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3060
                      uuid: GPU-02cb0d7a-f2df-2547-abf0-b0f13bec5cc8
                host: kslab-dev-server
                memory:
                    total: "67221581824"
                os: Linux-6.14.0-34-generic-x86_64-with-glibc2.39
                program: /home/annie/NeuralForecasting/train.py
                python: CPython 3.10.19
                root: /home/annie/NeuralForecasting
                startedAt: "2026-01-05T12:09:16.812802Z"
                writerId: 33hx5zsjqi0vo617lec41pux18m0s9vd
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
            "4": 3.10.19
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
architecture:
    value: amag
dataset:
    value: affi
epochs:
    value: 150
learning_rate:
    value: 0.001
loss_type:
    value: weighted_mse
